# exampleSite/config.yaml
baseURL: https://blog.contre.io
languageCode: en-US
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  es:
    disabled: false
    languageCode: es-ES
    languageDirection: ltr
    languageName: Español
    # params:
    #   subtitle: Lectur
    title: Contre
    weight: 1
    menus:
      main:
      - identifier: home
        name: Inicio
        url: /es
        weight: 1
      - identifier: posts
        name: Publicaciones
        url: /es/posts/
        weight: 3
      - identifier: rss
        name: RSS
        url: /es/posts/index.xml
        weight: 4
      - identifier: EN
        name: English
        url: /en
        weight: 5
  en:
    disabled: false
    languageCode: en
    languageDirection: ltr
    languageName: English
    # params:
    #   subtitle: Reference, Tutorials, and Explanations
    title: Contre
    weight: 0
    menus:
      main:
      - identifier: home
        name: Home
        url: /en
        weight: 1
      # - identifier: about
      #   name: About
      #   url: /about/
        # weight: 2
      - identifier: posts
        name: Posts
        url: /en/posts/
        weight: 3
      - identifier: rss
        name: RSS
        url: /en/posts/index.xml
        weight: 4
      - identifier: ES
        name: Spanish
        url: /es
        weight: 5
theme: smigle
themesDir: themes
title: Contre
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: rss
      name: RSS
      url: /posts/index.xml
      weight: 4
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 5
translationKey: about
params:
  abbrDateFmt: "Jan 2"
  author: "Blog Author"
  brandIconFile: "images/img.svg"
  dateFmt: "2006-01-02"
  subtitle: "|||||||||||"
 # customStylesheets: # Use to override theme styles, like logo size
 #   - "css/custom.css"
  # social:
  #   - name: Here
  #     url: https://blog.contre.io
